# .github/workflows/deploy.yml
name: CI & Deploy

on:                  # триггер — push в main
  push:
    branches: [ main ]

jobs:
  test:              # 1-й job: тесты
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: pip install -r requirements.txt
      - run: pytest

  deploy:            # 2-й job: выкладка
    needs: test
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
      USER: ${{ secrets.SSH_USER }}
      KEY:  ${{ secrets.SSH_KEY }}
      SERVICE: ${{ secrets.SERVICE_NAME }}
    steps:
      - uses: actions/checkout@v4

      # копируем проект (инкрементально, без лишних файлов)
      - name: Upload code to VPS
        uses: appleboy/scp-action@v0.1.1  # :contentReference[oaicite:0]{index=0}
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USER }}
          key: ${{ env.KEY }}
          source: "."
          target: "/opt/portal"
          strip_components: 1             # не создаёт лишнюю папку

      # выполняем команды внутри VPS
      - name: SSH – migrate & restart
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USER }}
          key: ${{ env.KEY }}
          script: |
            cd /opt/portal
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput
            sudo systemctl restart $SERVICE
